config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/matteogrisenti/Deliveroo-Plugin:
      branch: master
      repo: https://github.com/matteogrisenti/Deliveroo-Plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-taupe-woodpecker.sh
        container: qc.acc_snappy-fuchsia-beetle
  QC.Doc:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-eggplant-bongo.sh
        container: qc.doc_greasy-copper-crocodile
      github.com/matteogrisenti/Deliveroo-Plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-white-drever.sh
        container: qc.doc_stealthy-violet-nightingale
      github.com/matteogrisenti/Deliveroo-Plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ruby-centipede.sh
        container: qc.doc_snoopy-auburn-jaguar
  QC.Lic:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-amaranth-civet.sh
        container: qc.lic_cloudy-apricot-avocet
  QC.Sty:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-aqua-cassowary.sh
        container: qc.sty_lanky-amaranth-mau
      github.com/matteogrisenti/Deliveroo-Plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-flax-squirrel.sh
        container: qc.sty_gloppy-teal-goat
  QC.Ver:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-viridian-paradise.sh
        container: qc.ver_gamy-cerulean-gorilla
timeout: 5400
